// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Group struct {
	ID         int32              `json:"id"`
	Name       string             `json:"name"`
	WordsCount int32              `json:"words_count"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type StudyActivity struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Url       string             `json:"url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type StudySession struct {
	ID              int32              `json:"id"`
	GroupID         pgtype.Int4        `json:"group_id"`
	StudyActivityID pgtype.Int4        `json:"study_activity_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Word struct {
	ID        int32              `json:"id"`
	Malay     string             `json:"malay"`
	Jawi      string             `json:"jawi"`
	English   string             `json:"english"`
	Parts     []byte             `json:"parts"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type WordGroup struct {
	WordID    int32              `json:"word_id"`
	GroupID   int32              `json:"group_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WordReviewItem struct {
	ID             int32              `json:"id"`
	WordID         pgtype.Int4        `json:"word_id"`
	StudySessionID pgtype.Int4        `json:"study_session_id"`
	Correct        bool               `json:"correct"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
