// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	AddWordToGroup(ctx context.Context, arg AddWordToGroupParams) error
	CreateGroup(ctx context.Context, name string) (Group, error)
	CreateStudyActivity(ctx context.Context, arg CreateStudyActivityParams) (StudyActivity, error)
	CreateStudySession(ctx context.Context, arg CreateStudySessionParams) (StudySession, error)
	CreateWord(ctx context.Context, arg CreateWordParams) (Word, error)
	CreateWordReview(ctx context.Context, arg CreateWordReviewParams) (WordReviewItem, error)
	DeleteGroup(ctx context.Context, id int32) error
	DeleteStudyActivity(ctx context.Context, id int32) error
	DeleteWord(ctx context.Context, id int32) error
	GetGroup(ctx context.Context, id int32) (Group, error)
	GetGroupsByWord(ctx context.Context, arg GetGroupsByWordParams) ([]Group, error)
	GetLastStudySession(ctx context.Context) (GetLastStudySessionRow, error)
	GetQuickStats(ctx context.Context) (GetQuickStatsRow, error)
	GetSessionReviews(ctx context.Context, arg GetSessionReviewsParams) ([]GetSessionReviewsRow, error)
	GetStudyActivity(ctx context.Context, id int32) (StudyActivity, error)
	GetStudyProgress(ctx context.Context) (GetStudyProgressRow, error)
	GetStudySession(ctx context.Context, id int32) (StudySession, error)
	GetWord(ctx context.Context, id int32) (Word, error)
	GetWordsByGroup(ctx context.Context, arg GetWordsByGroupParams) ([]Word, error)
	ListGroups(ctx context.Context, arg ListGroupsParams) ([]Group, error)
	ListStudyActivities(ctx context.Context, arg ListStudyActivitiesParams) ([]StudyActivity, error)
	ListStudySessions(ctx context.Context, arg ListStudySessionsParams) ([]ListStudySessionsRow, error)
	ListWords(ctx context.Context, arg ListWordsParams) ([]Word, error)
	RemoveWordFromGroup(ctx context.Context, arg RemoveWordFromGroupParams) error
	SearchWords(ctx context.Context, arg SearchWordsParams) ([]Word, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	UpdateStudyActivity(ctx context.Context, arg UpdateStudyActivityParams) (StudyActivity, error)
	UpdateWord(ctx context.Context, arg UpdateWordParams) (Word, error)
}

var _ Querier = (*Queries)(nil)
