version: "3.8"

services:
  vllm-cpu:
    image: superumi/vllm-cpu:latest
    ports:
      - "8000:8000"
    environment:
      HF_TOKEN: ${HF_TOKEN}
      VLLM_CPU_DISABLE_AVX512: "true"
    # command: ["python3", "-m", "vllm.entrypoints.api_server", "--model", "google/gemma-2-9b", "--dtype", "bfloat16"]
    command: ["--model", "mesolitica/mallam-1.1B-4096", "--dtype", "bfloat16"]

  opea-nginx-server:
    image: opea/nginx:latest
    container_name: opea-nginx-server
    ports:
      - "${NGINX_PORT:-80}:80"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - FRONTEND_SERVICE_IP=${FRONTEND_SERVICE_IP}
      - FRONTEND_SERVICE_PORT=${FRONTEND_SERVICE_PORT}
      - BACKEND_SERVICE_NAME=${BACKEND_SERVICE_NAME}
      - BACKEND_SERVICE_IP=${BACKEND_SERVICE_IP}
      - BACKEND_SERVICE_PORT=${BACKEND_SERVICE_PORT}
      - DATAPREP_SERVICE_IP=${DATAPREP_SERVICE_IP}
      - DATAPREP_SERVICE_PORT=${DATAPREP_SERVICE_PORT}
    ipc: host
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount NGINX config
    depends_on:
      - vllm-cpu
    networks:
      - default
  
  whisper-service:
    image: ${REGISTRY:-opea}/whisper:${TAG:-latest}
    container_name: whisper-service
    ports:
      - "7066:7066"
    ipc: host
    depends_on:
      - opea-nginx-server
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
    restart: unless-stopped
  
  espeak-service:
    image: superumi/espeak-malay:latest
    container_name: espeak-service
    ports:
      - "7055:7055"
    ipc: host
    depends_on:
      - opea-nginx-server
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
    restart: unless-stopped

networks:
  default:
    driver: bridge