# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  ollama-server:
    image: ollama/ollama
    container_name: ollama-server
    ports:
      - ${LLM_ENDPOINT_PORT:-8008}:11434
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      LLM_MODEL_ID: ${LLM_MODEL_ID}
      host_ip: ${host_ip}

  # opea-nginx-server:
  #   image: opea/nginx:latest
  #   container_name: opea-nginx-server
  #   ports:
  #     - "${NGINX_PORT:-80}:80"
  #   environment:
  #     - no_proxy=${no_proxy}
  #     - https_proxy=${https_proxy}
  #     - http_proxy=${http_proxy}
  #     - FRONTEND_SERVICE_IP=${FRONTEND_SERVICE_IP}
  #     - FRONTEND_SERVICE_PORT=${FRONTEND_SERVICE_PORT}
  #     - BACKEND_SERVICE_NAME=${BACKEND_SERVICE_NAME}
  #     - BACKEND_SERVICE_IP=${BACKEND_SERVICE_IP}
  #     - BACKEND_SERVICE_PORT=${BACKEND_SERVICE_PORT}
  #     - DATAPREP_SERVICE_IP=${DATAPREP_SERVICE_IP}
  #     - DATAPREP_SERVICE_PORT=${DATAPREP_SERVICE_PORT}
  #   ipc: host
  #   restart: always

  # guardrails-bias-detection-server:
  #   image: ${REGISTRY:-opea}/guardrails-bias-detection:${TAG:-latest}
  #   container_name: guardrails-bias-detection-server
  #   ports:
  #     - "${BIAS_DETECTION_PORT:-9092}:9092"
  #   ipc: host
  #   environment:
  #     no_proxy: ${no_proxy}
  #     http_proxy: ${http_proxy}
  #     https_proxy: ${https_proxy}
  #     HUGGINGFACEHUB_API_TOKEN: ${HF_TOKEN}
  #   restart: unless-stopped

  # guardrails-server:
  #   image: ${REGISTRY:-opea}/guardrails:${TAG:-latest}
  #   container_name: guardrails-server
  #   ports:
  #     - "${GUARDRAILS_PORT:-9090}:9090"
  #   ipc: host
  #   environment:
  #     no_proxy: ${no_proxy}
  #     http_proxy: ${http_proxy}
  #     https_proxy: ${https_proxy}
  #     SAFETY_GUARD_ENDPOINT: ${SAFETY_GUARD_ENDPOINT}
  #     SAFETY_GUARD_MODEL_ID: ${SAFETY_GUARD_MODEL_ID}
  #     GUARDRAILS_COMPONENT_NAME: "OPEA_LLAMA_GUARD"
  #   restart: unless-stopped
    
networks:
  default:
    driver: bridge